update golang to in-support versions (1.16 and 1.17)
microsoft/vscode-dev-containers pull request #1001
Opened 2021-08-18 17:29 UTC by joshspicer

context: https://github.com/microsoft/vscode-dev-containers/issues/1000

Updates our versions of `go` to track latest supported

### TODO
- [ ] Update [tracking issue](https://github.com/microsoft/vscode-dev-containers/issues/532)

2021-08-18 17:37 UTC, joshspicer commented
builds fine in remote containers 👍 
![image](https://user-images.githubusercontent.com/23246594/129945688-964cb9e2-ab1d-444e-b124-562732a908a3.png)

2021-08-18 17:53 UTC, Chuxel requested changes
Two things.

It looks like there's a bug in the go-debian script this exposed.  It turns out that `go version` emits a version of `go1.17` instead of `go1.17.0` like you'd normally expect.

Therefore this line

```
if [[ "1.16" > "$(go version | grep -oP 'go\K[0-9]+\.[0-9]+\.[0-9]+')" ]]; then
```
needs to make the last section of the semver optional. I think this should do it:
```
if [[ "1.16" > "$(go version | grep -oP 'go\K[0-9]+\.[0-9]+(\.[0-9]+)?')" ]]; then
```
Go 1.17 recommends using "go install" for CLIs instead of "go get", but older versions still need the old syntax. So this detects the actually installed version (since we may have skipped installing go itself) and only uses `go install` for go 1.16+.

The other is a minor tweak inline...

2021-08-18 17:53 UTC, Chuxel commented on containers/go/definition-manifest.json
> +	"variants": ["1.16", "1.17"],
```suggestion
	"variants": ["1.17", "1.16"],
```

The order here matters. The zero index is assigned "latest", so put 1.17 there.

2021-08-19 14:18 UTC, joshspicer commented
nice - that looks good
![image](https://user-images.githubusercontent.com/23246594/130084867-fb5dd0c7-57c0-45b9-ae0e-e53e8de8cda2.png)

2021-08-19 15:07 UTC, Chuxel approved these changes

2021-08-19 15:07 UTC, Chuxel commented
@joshspicer Looks good! Feel free to merge when ready!

2021-08-19 15:31 UTC, merged